# This is the network config written by 'subiquity'
network:
  ethernets:
    enp0s3:
      dhcp4: false
      addresses:
      - 172.16.1.10/24
      nameservers:
        addresses:
        - 172.16.1.1
        search: [maxime.ocean.lan]
      routes:
        - to: default
          via: 172.16.1.1
  version: 2
