# This is the network config written by 'subiquity'
network:
  renderer: networkd
  ethernets:
    enp0s3:
      dhcp4: true
    enp0s8:
      addresses:
      - 172.16.1.1/24
    enp0s9:
      addresses:
      - 165.134.0.1/16
      nameservers:
        addresses:
          - 165.134.0.1
        search: [maxime.ocean.lan]
      routes:
        - to: 172.16.2.0/24
          via: 165.134.0.2
  version: 2
