# This is the network config written by 'subiquity'
network:
  ethernets:
    enp0s3:
      dhcp4: true
    enp0s8:
      addresses:
      - 172.16.2.1/24
    enp0s9:
      addresses:
      - 165.134.0.2/24
      nameservers:
        addresses:
          - 127.0.0.1
        search: [maxime.mountain.lan]
      routes:
        - to: 172.16.1.0/24
          via: 165.134.0.1
  version: 2
