network:
  version: 2
  renderer: NetworkManager
  ethernets:
    enp0s3:
      dhcp4: false
    enp0s8:
      dhcp4: false
  bonds:
    bond0:
      interfaces:
        - enp0s3
        - enp0s8
      addresses:
        - 192.168.1.100/24
      nameservers:
        addresses:
        - 8.8.8.8
      parameters:
        mode: balance-rr
