network:
  version: 2
  renderer: NetworkManager
  ethernets:
    enp0s3:
      addresses:
      - 192.168.100.10 #Ipfixe
      nameservers:
        addresses:
        - 8.8.8.8
      routes:
        - to: default
          via: 192.168.100.1
    enp0s8:
      dhcp4: true